### ISSUE TITLE
first / left / right page margins

### ISSUE THREAD

**Issue by drom** [drom/datasheet#11]
### Need

Specific page margin for fist / left / right pages on print.

### Solution

Works in chrome:

```css
@page :left {
  margin: 1in 2in 1in 1in;
}

@page :right {
  margin: 1in 1in 1in 2in;
}

@page :first {
  margin: 1in 1.5in 1in 1.5in;
}
```
